Repository openshift/cli-manager-operator, pull requests merged in 2024-08, with the labels that each got.

#199 WRKLDS-1421: Serve metrics server in https
  bindata/assets/cli-manager/deployment.yaml
  bindata/assets/cli-manager/service.yaml
  bindata/assets/cli-manager/servicemonitor.yaml
Labels: approved, jira/valid-reference, lgtm

#209 WRKLDS-1421: Prepare tekton files specific to release-4.17 branch
  .tekton/cli-manager-operator-4-17-pull-request.yaml
  .tekton/cli-manager-operator-4-17-push.yaml
  .tekton/cli-manager-operator-bundle-4-17-pull-request.yaml
  .tekton/cli-manager-operator-bundle-4-17-push.yaml
  bundle.Dockerfile
Labels: cherry-pick-approved, jira/valid-bug, approved, jira/valid-reference, lgtm, backport-risk-assessed

#213 [release-4.17] WRKLDS-1421: Add required image labels in Dockerfile
  Dockerfile
Labels: cherry-pick-approved, jira/valid-bug, approved, jira/valid-reference, lgtm, backport-risk-assessed

#212 WRKLDS-1421: Add required image labels in Dockerfile
  Dockerfile
Labels: approved, jira/valid-reference, lgtm

#223 WRKLDS-1421: Update catalog index with new release 0.1.0 clio
  v4.17/catalog/cli-manager/index.yaml
Labels: approved, jira/valid-reference, lgtm

#224 WRKLDS-1421: Fix alignment issue in tekton files for fbc
  .tekton/cli-manager-operator-fbc-4-17-pull-request.yaml
  .tekton/cli-manager-operator-fbc-4-17-push.yaml
Labels: approved, jira/valid-reference, lgtm

#219 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/cli-manager-operator-bundle-pull-request.yaml
  .tekton/cli-manager-operator-bundle-push.yaml
  .tekton/cli-manager-operator-pull-request.yaml
  .tekton/cli-manager-operator-push.yaml
Labels: ok-to-test, approved, lgtm

#259 WRKLDS-1421: Update catalog index with new release
  v4.17/catalog/cli-manager/index.yaml
Labels: approved, jira/valid-reference, lgtm

#260 WRKLDS-1421: Update CSV according to new rbac changes
  manifests/cli-manager-operator.clusterserviceversion.yaml
Labels: approved, jira/valid-reference, lgtm

#262 WRKLDS-1421: Get new 0.1.0 release for fbc
  v4.17/catalog/cli-manager/index.yaml
Labels: approved, jira/valid-reference, lgtm

#270 WRKLDS-1421: Use bundle image with digest
  README.md
  v4.17/catalog.Dockerfile
  v4.17/catalog/cli-manager/index.yaml
Labels: approved, jira/valid-reference, lgtm

#271 WRKLDS-1421: Fix rbac typo in endpoints
  manifests/cli-manager-operator.clusterserviceversion.yaml
Labels: approved, jira/valid-reference, lgtm

#273 WRKLDS-1421: Prepare a new 0.1.0 release
  v4.17/catalog/cli-manager/index.yaml
Labels: approved, jira/valid-reference, lgtm
