Repository openshift/cli-manager-operator, pull requests merged in 2025-03, with the labels that each got.

#661 RELEASE BLOCKER(March 17, 2025): Add fbc-target-index-pruning-check to FBC pipelines
  .tekton/cli-manager-operator-fbc-4-18-pull-request.yaml
  .tekton/cli-manager-operator-fbc-4-18-push.yaml
Labels: ok-to-test, approved, lgtm

#662 NO-JIRA: Prepare for 0.1.1 release for 4.18
  Makefile
  bundle.Dockerfile
  manifests/cli-manager-operator.clusterserviceversion.yaml
Labels: cherry-pick-approved, jira/valid-bug, approved, jira/valid-reference, lgtm, backport-risk-assessed

#664 WRKLDS-1662: Add required Konflux tasks for release
  .tekton/cli-manager-operator-bundle-pull-request.yaml
  .tekton/cli-manager-operator-bundle-push.yaml
  .tekton/cli-manager-operator-pull-request.yaml
  .tekton/cli-manager-operator-push.yaml
Labels: approved, jira/valid-reference, lgtm

#666 WRKLDS-1662: Remove redundant task from bundle pipeline
  .tekton/cli-manager-operator-bundle-pull-request.yaml
  .tekton/cli-manager-operator-bundle-push.yaml
Labels: approved, lgtm

#669 WRKLDS-1662: Remove redundant bundle task
  .tekton/cli-manager-operator-4-18-pull-request.yaml
  .tekton/cli-manager-operator-4-18-push.yaml
  .tekton/cli-manager-operator-bundle-4-18-pull-request.yaml
  .tekton/cli-manager-operator-bundle-4-18-push.yaml
Labels: cherry-pick-approved, jira/valid-bug, approved, jira/valid-reference, lgtm, backport-risk-assessed

#670 Trigger pipelinerun to get new snapshot
  .tekton/cli-manager-operator-4-18-pull-request.yaml
  .tekton/cli-manager-operator-4-18-push.yaml
  .tekton/cli-manager-operator-bundle-4-18-pull-request.yaml
  .tekton/cli-manager-operator-bundle-4-18-push.yaml
Labels: cherry-pick-approved, jira/valid-bug, approved, lgtm, backport-risk-assessed

#672 Revert back to original working configuration
  .tekton/cli-manager-operator-bundle-pull-request.yaml
  .tekton/cli-manager-operator-bundle-push.yaml
  .tekton/cli-manager-operator-pull-request.yaml
  .tekton/cli-manager-operator-push.yaml
Labels: approved, lgtm

#677 WRKLDS-1662: Prepare for 0.1.1 release for 4.18
  .tekton/cli-manager-operator-fbc-4-18-pull-request.yaml
  .tekton/cli-manager-operator-fbc-4-18-push.yaml
  v4.18/catalog/cli-manager/index.yaml
Labels: approved, jira/valid-reference, lgtm

#678 NO-JIRA: Add required sast tasks
  .tekton/cli-manager-operator-bundle-pull-request.yaml
  .tekton/cli-manager-operator-bundle-push.yaml
  .tekton/cli-manager-operator-pull-request.yaml
  .tekton/cli-manager-operator-push.yaml
Labels: approved, jira/valid-reference, lgtm
